"""Auto-graph builder package for Contextus."""

from .config import BuilderConfig
from .preprocessor import ElementPreprocessor
from .audit import ChunkAuditExporter, ChunkAuditRow
from .node_candidate import NodeCandidate, NodeCandidateBuilder
from .chunker import (
    ActiveConcept,
    BoundaryCandidate,
    BoundaryDecision,
    BoundaryElementView,
    BoundaryPreliminaryDecision,
    BoundarySignals,
    ChunkRepairDecision,
    ConceptProbeDecision,
    DocumentChunker,
    RefinedChunkGroup,
    TentativeBlock,
)
from .node_builder import NodeBuilder
from .edge_builder import EdgeBuilder
from .evidence import (
    ContextAttachment,
    ContextPackageSegment,
    ElementSignalRecord,
    EvidenceContextPackage,
    EvidenceHandle,
    EvidenceHandleBuilder,
    EvidencePipelineResult,
    HeadingCandidate,
    ListSignal,
    MarkerSpan,
)
from .evidence_eval import (
    EvidencePromptCase,
    EvidencePromptEvaluation,
    EvidencePromptHit,
    EvidencePromptSuiteResult,
    RetrievalCollectionEvaluation,
    RetrievalComparisonSuiteResult,
    RetrievalEvalHit,
    RetrievalEvalItem,
    default_prompt_cases,
    evaluate_prompt_case,
    evaluate_prompt_suite,
    evaluate_retrieval_collection,
    evaluate_retrieval_collections,
    package_retrieval_items,
    render_retrieval_comparison_markdown,
    render_prompt_suite_markdown,
)
from .query_assembly import (
    ConsensusKnnPropositionEvidenceAssembler,
    PropositionQueryTimeEvidenceAssembler,
    QueryAssembledPackage,
    QueryAssemblyDecision,
    QueryEvidenceProposition,
    QueryAssemblyResult,
    QueryTimeEvidenceAssembler,
)
from .pipeline import AutoGraphBuilder
from .structural import DoclingStructuralEnricher, ElementStructuralAnnotation, StructuralEnrichmentResult

__all__ = [
    "AutoGraphBuilder",
    "ActiveConcept",
    "BoundaryCandidate",
    "BoundaryDecision",
    "BoundaryElementView",
    "BoundaryPreliminaryDecision",
    "BoundarySignals",
    "BuilderConfig",
    "ChunkAuditExporter",
    "ChunkAuditRow",
    "ChunkRepairDecision",
    "ConceptProbeDecision",
    "ConsensusKnnPropositionEvidenceAssembler",
    "ContextAttachment",
    "ContextPackageSegment",
    "DocumentChunker",
    "DoclingStructuralEnricher",
    "EdgeBuilder",
    "ElementSignalRecord",
    "ElementStructuralAnnotation",
    "ElementPreprocessor",
    "EvidenceContextPackage",
    "EvidenceHandle",
    "EvidenceHandleBuilder",
    "EvidencePipelineResult",
    "EvidencePromptCase",
    "EvidencePromptEvaluation",
    "EvidencePromptHit",
    "EvidencePromptSuiteResult",
    "HeadingCandidate",
    "ListSignal",
    "MarkerSpan",
    "NodeBuilder",
    "NodeCandidate",
    "NodeCandidateBuilder",
    "PropositionQueryTimeEvidenceAssembler",
    "QueryAssembledPackage",
    "QueryAssemblyDecision",
    "QueryEvidenceProposition",
    "QueryAssemblyResult",
    "QueryTimeEvidenceAssembler",
    "RefinedChunkGroup",
    "RetrievalCollectionEvaluation",
    "RetrievalComparisonSuiteResult",
    "RetrievalEvalHit",
    "RetrievalEvalItem",
    "StructuralEnrichmentResult",
    "TentativeBlock",
    "default_prompt_cases",
    "evaluate_prompt_case",
    "evaluate_prompt_suite",
    "evaluate_retrieval_collection",
    "evaluate_retrieval_collections",
    "package_retrieval_items",
    "render_retrieval_comparison_markdown",
    "render_prompt_suite_markdown",
]
